### ISSUE TITLE
Make artifact available on Maven

### ISSUE THREAD

**Issue by scheleaap** [monix/monix-connect#623]
The button in the README points to https://search.maven.org/search?q=a:monix-connect*, however it appears that the artifact is not available on Maven.

Can you please publish versions to Maven?

**Comment by paualarco** [comment]
Hi @scheleaap, thanks for pointing that. There was some problems that made us stop publishing the aggregated jar, but I will look into it or either remove that part of the docs. 
I would recommend to just pick up the connector you need, in order to avoid pulling transitive dependencies in between.
[See for example aws-s3](https://oss.sonatype.org/#nexus-search;gav~io.monix~monix-s3_2.12~~~~kw,versionexpand).

**Comment by scheleaap** [comment]
Ah, thanks for pointing out the individual artifacts! I did not notice there is a specialized artifact on the (in my case) MongoDB page.

**Comment by paualarco** [comment]
No problem @scheleaap
